### ISSUE TITLE
How does one set Let'sEncrypt to auto renewing via homebase?

### ISSUE THREAD

**Issue by edouerd** [beakerbrowser/homebase#14]
I'm unsure where homebase installs Let'sEncrypt, or which directory one might manually renew their certs.

Perhaps make autorenewing certs an option in `homebase.yml`?

**Comment by pfrazee** [comment]
Homebase is meant to auto-renew without intervention. Did it not do that for you?

**Comment by edouerd** [comment]
Apologies for delay in response, have been traveling!

I believe homebase hasn't auto-renewed, or hasn't explicitly let me know it has actually renewed, as I continue to receive emails about the cert's expiration date looming.

**Comment by edouerd** [comment]
Additionally, I'm wondering if my using homebase v. 1.0.0 makes a difference — I can try migrating to see how it affects my certificate renewal.

**Comment by pfrazee** [comment]
Oh right, those emails. IIRC, the module that homebase uses will auto-renew when the cert finally expires. Maybe we can dig into the module's API and find a way to either renew earlier, or to stop those emails from coming.

**Comment by edouerd** [comment]
Amazing, that's great to know! I'll report back in the meantime if things end up weird. Thanks!
