### ISSUE TITLE
.dat folder shows up in httpMirror, if there is a file structure

### ISSUE THREAD

**Issue by DKunin** [beakerbrowser/homebase#16]
So when serving dat version - the .dat folder is invisible and inaccessible, and when mirrorred you can peek inside

<img width="330" alt="screen shot 2018-08-20 at 15 24 49" src="https://user-images.githubusercontent.com/996993/44340356-42a12080-a48d-11e8-99e6-8fbd76c4cefb.png">
<img width="308" alt="screen shot 2018-08-20 at 15 24 57" src="https://user-images.githubusercontent.com/996993/44340358-4339b700-a48d-11e8-9ec9-ec6c11400d7a.png">
<img width="389" alt="screen shot 2018-08-20 at 15 26 32" src="https://user-images.githubusercontent.com/996993/44340411-711efb80-a48d-11e8-8946-d9122cf1b29f.png">

I am not sure that this is ok, I understand that getting these files is not the same as getting private keys, but still, maybe there is a way to ignore the folder?

**Comment by pfrazee** [comment]
Oof you're right. Yeah I'll get that filtered out.

**Comment by DKunin** [comment]
🔥 Thtanks a lot!
