### ISSUE TITLE
Invalid email issue while adding SSL

### ISSUE THREAD

**Issue by Shubham-kamboj** [beakerbrowser/homebase#25]
I am trying to add SSL to this domain with this email id. Whereas Domain is added on our server properly and email is also verified. But I don't know why am getting this error again and again. Here are logs of SSL server:-

Domain is  [ 'farmersdirect.net', 'www.farmersdirect.net' ] object
0|index    | customEmail is  mkr1279@hotmail.com
0|index    | mmmiiinnn  timeeee 7689600000
**0|index    | [acme-v2] (E_STATE_INVALID) challenge state: 'invalid'**
0|index    | [acme-v2] handled(?) rejection as errback:
0|index    | Error: [acme-v2] [error] unacceptable challenge state 'invalid'
0|index    |     at /var/www/storehippo/app/servers/ssl_certificate/node_modules/acme-v2/node.js:374:31
0|index    |     at <anonymous>
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
0|index    | { Error: socket hang up
0|index    |     at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
0|index    |     at Object.onceWrapper (events.js:313:30)
0|index    |     at emitNone (events.js:111:20)
0|index    |     at TLSSocket.emit (events.js:208:7)
0|index    |     at endReadableNT (_stream_readable.js:1055:12)
0|index    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
0|index    |   code: 'ECONNRESET',
0|index    |   path: null,
0|index    |   host: 'localhost',
0|index    |   port: 443,
0|index    |   localAddress: undefined } 'respppppppp' undefined
0|index    | { Error: ENOENT: no such file or directory, open '/root/acme/etc/live/farmersdirect.net/fullchain.pem'

**Comment by pfrazee** [comment]
You run farmersdirect.net?

If so, homebase's https requires that it's given access to port 443 and made the main server. If you don't want to do that, I'd just turn off letsencrypt and https and let your existing server handle https.

**Comment by Shubham-kamboj** [comment]
Hi 
I don't get your point exactly.

**Comment by pfrazee** [comment]
Are you the owner of the farmersdirect.net domain name?
