### ISSUE TITLE
decrentralized homebase

### ISSUE THREAD

**Issue by ShalokShalom** [beakerbrowser/homebase#33]
Hi there :) 

You created an awesome tool set with your projects and hence you are supporting distributed approaches in general:

Is it likely that this service becomes distributed as well?

**Comment by pfrazee** [comment]
@ShalokShalom That's basically what the IPFS team is trying to do with FileCoin. I'm less concerned with making a decentralized & distributed homebase because I think the important thing is the flexibility that dat provides -- you can change one homebase for another with no problem.
