### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by rh0** [beakerbrowser/homebase#6]
This seems to require nodejs 8.x or greater to run.  I attempted with nodejs 6.x but recieved:
```
/usr/lib/node_modules/@beaker/homebase/lib/vhosts/dat.js:65
  return async function (req, res) {
               ^^^^^^^^

SyntaxError: Unexpected token function
```
After upgrading to nodejs 8 everything seems fine.  I mention this only because the readme states nodejs 4.9.1 or greater and that might be misleading.

**Comment by pfrazee** [comment]
Thanks, I'll update the readme.
